twitter:
  consumer_key: OpJlhPRuM44KP7mozTHBw
  consumer_secret: i1wRlBPxhyq5hDp0kfkskyuVn09GatLruyirZ1ksk
  oauth_token: 14178534-npciHenvs1kTXmRvqspWLLxZKTZJVyL4vwseV5CEs
  oauth_token_secret: zQFQh6l5brX4Sf45v3mBVlAZvDltT9YTqoCtR0PCNCc
